### ISSUE TITLE
Synthetic test against Nginx using docker-compose

### ISSUE THREAD

**Issue by derekargueta** [derekargueta/irm#29]
[Docker-compose](https://docs.docker.com/compose/) is a tool for orchestrating multiple containers. Use docker-compose to set up two containers:
1) an Nginx container using the [public image](https://hub.docker.com/_/nginx).
2) a container running a new Go binary that runs integration tests.

The new integration test will run the probes against the Nginx container and verify that it matches what Nginx is configured with. For example, the Nginx container will be configured to have TLS 1.3 disabled, and the integration test will confirm that the TLS 1.3 probe fails.

**Comment by Tavofn** [comment]
sent collaboration invite to see code on my git
